# Generated by Django 4.2 on 2023-04-04 18:52

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("publisher", models.TextField()),
                (
                    "book_slug",
                    models.SlugField(max_length=255, verbose_name="Book Slug"),
                ),
                ("ISBN", models.CharField(max_length=255, unique=True)),
                ("year_of_publication", models.CharField(max_length=255)),
                ("total_rating", models.CharField(max_length=255, null=True)),
                ("img_s", models.CharField(max_length=255)),
                ("img_m", models.CharField(max_length=255)),
                ("img_l", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("ISBN", models.CharField(max_length=255, unique=True)),
                ("rating", main_app.models.IntegerRangeField(default=0)),
            ],
        ),
    ]
