# Generated by Django 4.2 on 2023-04-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratings",
            name="ISBN",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ratings",
            name="user_id",
            field=models.CharField(max_length=255),
        ),
    ]
